### ISSUE TITLE
Display multiple affinities

### ISSUE THREAD

**Issue by BlueWinds** [wmtorode/mechaffinity#8]
BTA has both chasis affinities and global ones. For example:

Global - Attuned (5): Get a +1 bonus to all skills
Chassis - Nimble (8): +15% jump distance

When the user hits 8 missions, "Nimble" is shown, while Attuned disappears (while still having an effect). It would be nice to see both, so that we don't have to edit "and +1 to all skills" into each individual chassis affinity.

One potential solution would be to display the highest value in each "category" for each mech - eg, the best chassis affinity _and_ best global affinity. This would also support more flexible layouts, eg. adding Mastered (15): +2 to all skills, which in the current setup, would hide Nimble, and we'd have no way to display that the jumping bonus still applies.

**Comment by wmtorode** [comment]
Added setting to show all affinities on the pilot dossier
